import { useCallback, useEffect, useRef, useState } from 'react';
import { apiFetch } from '../../utils/request';

export default function ResearchReportsPage() {
  const [reports, setReports] = useState([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const fileRef = useRef(null);
  const load = useCallback(async () => { const res = await apiFetch('/api/research-workspace/myreports', {}, 10000, 1); if (res.ok) setReports(res.data?.data || []); else setError(res.error || '研报读取失败'); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  const upload = async file => { if (!file) return; setUploading(true); setError(''); try { const content = await readFile(file); const res = await apiFetch('/api/research-workspace/myreports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: file.name, content_b64: content }) }); if (!res.ok) throw new Error(res.error || '上传失败'); await load(); } catch (e) { setError(e.message); } finally { setUploading(false); } };
  const remove = async id => { if (!window.confirm('确定删除这份本地研报吗？')) return; const res = await apiFetch(`/api/research-workspace/myreports/${id}`, { method: 'DELETE' }); if (!res.ok) setError(res.error || '删除失败'); else load(); };
  return <div className="space-y-3 fade-in"><div className="flex items-center justify-between gap-2"><div><div className="text-xs" style={{ color: 'var(--text-muted)' }}>研究工作区</div><h2 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>我的研报</h2><div className="text-xs" style={{ color: 'var(--text-muted)' }}>文件只存本机，不上传到外部服务</div></div><div className="flex gap-2"><input ref={fileRef} type="file" className="hidden" onChange={e => upload(e.target.files?.[0])} /><button onClick={() => fileRef.current?.click()} disabled={uploading} className="rounded border px-2.5 py-1.5 text-xs" style={{ borderColor: 'var(--accent-blue)', color: 'var(--accent-blue)' }}>{uploading ? '上传中…' : '上传研报'}</button><button onClick={load} className="rounded border px-2.5 py-1.5 text-xs" style={{ borderColor: 'var(--border-color)', color: 'var(--text-secondary)' }}>刷新</button></div></div>{error && <div className="rounded border px-3 py-2 text-xs" style={{ borderColor: '#ef444466', background: '#ef444412', color: '#b91c1c' }}>{error}</div>}{loading ? <div className="p-8 text-center text-xs" style={{ color: 'var(--text-muted)' }}>正在读取研报…</div> : <div className="rounded-lg border" style={{ borderColor: 'var(--border-color)', background: 'var(--bg-card)' }}>{reports.map(report => <div key={report.id} className="flex items-center justify-between gap-3 border-b px-3 py-2.5" style={{ borderColor: 'var(--border-color)' }}><div className="min-w-0"><div className="truncate text-xs font-medium" style={{ color: 'var(--text-primary)' }}>{report.name}</div><div className="mt-0.5 text-[10px]" style={{ color: 'var(--text-muted)' }}>{report.industry || '未分类'} · {formatSize(report.size)}</div></div><div className="flex shrink-0 gap-1.5"><a href={`/api/research-workspace/myreports/file/${report.id}`} target="_blank" rel="noreferrer" className="rounded border px-2 py-1 text-[10px] no-underline" style={{ borderColor: 'var(--border-color)', color: 'var(--accent-blue)' }}>打开</a><button onClick={() => remove(report.id)} className="rounded border px-2 py-1 text-[10px]" style={{ borderColor: '#ef444466', color: '#b91c1c' }}>删除</button></div></div>)}{!reports.length && <div className="p-8 text-center text-xs" style={{ color: 'var(--text-muted)' }}>暂无本地研报，点击右上角上传</div>}</div>}</div>;
}
function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function formatSize(size) { if (!size) return '—'; if (size > 1024 * 1024) return `${(size / 1024 / 1024).toFixed(1)} MB`; return `${Math.ceil(size / 1024)} KB`; }
