import { useCallback, useEffect, useState } from 'react';
import { apiFetch } from '../../utils/request';

export default function ResearchRadarPage() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (force = false) => { force ? setRefreshing(true) : setLoading(true); const res = await apiFetch(force ? '/api/research-workspace/radar/refresh' : '/api/research-workspace/radar', {}, 20000, 1); setData(res.ok ? res.data?.data || res.data : null); force ? setRefreshing(false) : setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  if (loading) return <div className="p-8 text-center text-xs" style={{ color: 'var(--text-muted)' }}>正在读取资讯雷达…</div>;
  const groups = data?.industries || [];
  return <div className="space-y-3 fade-in"><div className="flex items-center justify-between gap-2"><div><div className="text-xs" style={{ color: 'var(--text-muted)' }}>研究工作区 / 板块中心</div><h2 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>细分板块雷达</h2><div className="text-xs" style={{ color: 'var(--text-muted)' }}>按主题聚合近期开源资讯，不混入选股评分</div></div><button onClick={() => load(true)} disabled={refreshing} className="rounded border px-2.5 py-1.5 text-xs" style={{ borderColor: 'var(--border-color)', color: 'var(--text-secondary)' }}>{refreshing ? '刷新中…' : '刷新资讯'}</button></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{groups.map(group => <section key={group.key} className="rounded-lg border p-3" style={{ borderColor: 'var(--border-color)', background: 'var(--bg-card)' }}><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-semibold" style={{ color: group.accent || 'var(--text-primary)' }}>{group.name}</h3><span className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{group.total ?? group.items?.length ?? 0} 条</span></div><div className="space-y-1">{(group.items || []).slice(0, 8).map((item, i) => <a key={`${item.title}-${i}`} href={item.url || '#'} target="_blank" rel="noreferrer" className="block border-b py-1.5 no-underline" style={{ borderColor: 'var(--border-color)' }}><div className="text-xs" style={{ color: 'var(--text-primary)' }}>{item.title}</div><div className="mt-0.5 text-[10px]" style={{ color: 'var(--text-muted)' }}>{item.time || ''} {item.summary ? `· ${item.summary}` : ''}</div></a>)}{!(group.items || []).length && <div className="py-3 text-center text-xs" style={{ color: 'var(--text-muted)' }}>暂无资讯</div>}</div></section>)}{!groups.length && <div className="rounded-lg border p-8 text-center text-xs md:col-span-2" style={{ borderColor: 'var(--border-color)', color: 'var(--text-muted)' }}>暂无雷达数据</div>}</div></div>;
}
