"""baseline: snapshot existing schema

Revision ID: 8bc02e0df999
Revises: 
Create Date: 2026-07-08 10:00:17.841153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc02e0df999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_trade_log_ts_date'), table_name='auto_trade_log')
    op.drop_index(op.f('ix_bs_backtest_results_dimension_run'), table_name='bs_backtest_results')
    op.drop_index(op.f('ix_leader_lifecycle_ts_date'), table_name='leader_lifecycle')
    op.drop_index(op.f('ix_sector_flow_net'), table_name='sector_flow', postgresql_where='(net_flow IS NOT NULL)')
    op.alter_column('stock_daily_kline', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'pct_chg',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'main_force_inflow',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.drop_index(op.f('idx_stock_daily_kline_date'), table_name='stock_daily_kline')
    op.drop_index(op.f('idx_stock_daily_kline_ts_date'), table_name='stock_daily_kline')
    op.drop_constraint(op.f('stock_daily_kline_ts_code_trade_date_key'), 'stock_daily_kline', type_='unique')
    op.create_index('ix_daily_kline_date', 'stock_daily_kline', ['trade_date'], unique=False)
    op.create_index(op.f('ix_stock_daily_kline_trade_date'), 'stock_daily_kline', ['trade_date'], unique=False)
    op.create_index(op.f('ix_stock_daily_kline_ts_code'), 'stock_daily_kline', ['ts_code'], unique=False)
    op.create_unique_constraint('uq_daily_kline_code_date', 'stock_daily_kline', ['ts_code', 'trade_date'])
    op.drop_index(op.f('ix_stock_flow_is_anomaly'), table_name='stock_flow', postgresql_where='(is_anomaly = true)')
    op.drop_index(op.f('ix_stock_flow_is_suspended'), table_name='stock_flow', postgresql_where='(is_suspended = true)')
    op.drop_column('stock_flow', 'is_delisted')
    op.drop_column('stock_flow', 'is_anomaly')
    op.drop_column('stock_flow', 'is_suspended')
    op.drop_index(op.f('ix_watchlist_signal_daily_sector_date'), table_name='watchlist_signal_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_watchlist_signal_daily_sector_date'), 'watchlist_signal_daily', ['sector', sa.literal_column('trade_date DESC')], unique=False)
    op.add_column('stock_flow', sa.Column('is_suspended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('stock_flow', sa.Column('is_anomaly', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('stock_flow', sa.Column('is_delisted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_stock_flow_is_suspended'), 'stock_flow', ['is_suspended'], unique=False, postgresql_where='(is_suspended = true)')
    op.create_index(op.f('ix_stock_flow_is_anomaly'), 'stock_flow', ['is_anomaly'], unique=False, postgresql_where='(is_anomaly = true)')
    op.drop_constraint('uq_daily_kline_code_date', 'stock_daily_kline', type_='unique')
    op.drop_index(op.f('ix_stock_daily_kline_ts_code'), table_name='stock_daily_kline')
    op.drop_index(op.f('ix_stock_daily_kline_trade_date'), table_name='stock_daily_kline')
    op.drop_index('ix_daily_kline_date', table_name='stock_daily_kline')
    op.create_unique_constraint(op.f('stock_daily_kline_ts_code_trade_date_key'), 'stock_daily_kline', ['ts_code', 'trade_date'])
    op.create_index(op.f('idx_stock_daily_kline_ts_date'), 'stock_daily_kline', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_stock_daily_kline_date'), 'stock_daily_kline', ['trade_date'], unique=False)
    op.alter_column('stock_daily_kline', 'main_force_inflow',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'pct_chg',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'close',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'low',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'high',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_daily_kline', 'open',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_sector_flow_net'), 'sector_flow', [sa.literal_column('net_flow DESC')], unique=False, postgresql_where='(net_flow IS NOT NULL)')
    op.create_index(op.f('ix_leader_lifecycle_ts_date'), 'leader_lifecycle', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('ix_bs_backtest_results_dimension_run'), 'bs_backtest_results', ['dimension', sa.literal_column('run_at DESC')], unique=False)
    op.create_index(op.f('ix_auto_trade_log_ts_date'), 'auto_trade_log', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    # ### end Alembic commands ###
